# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ARHome' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for ARHome
  pod 'Alamofire'
  pod 'SDWebImage'

  target 'ARHomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARHomeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
